#!/bin/sh

config_dir="$HOME/.i3/configs"
config="$HOME/.i3/config"
i3_regen_config="$(readlink -f $0) $@"

gen_config() {
	cat << EOF > "$config"
# THIS FILE WAS GENERATED AUTOMATICALLY WITH THIS COMMAND:
# $i3_regen_config

# DO NOT EDIT THIS FILE DIRECTLY, AS IT IS OVERWRITTEN BY ~/.xsession, AS WELL
# AS ANY TIME THE RELOAD OR RESTART KEYBINDINGS ARE PRESSED!

# YOU SHOULD EDIT THE CONFIG FRAGMENTS UNDER $config_dir INSTEAD.

set \$i3_regen_config $i3_regen_config
EOF

	for fragment in "$@"; do
		echo -e "\n# ===== i3 CONFIG FRAGMENT -- $config_dir/$fragment =====\n" >> "$config"
		cat "$config_dir/$fragment" >> "$config"
	done
}

if [ $# -eq 0 ]; then
	gen_config base generic
else
	gen_config base "$@"
fi

exit 0
